### ISSUE TITLE
I think i have the key in the bar of la plage ^^

### ISSUE THREAD

**Issue by Bramas** [perelo/MainframeSimulator#1]

**Comment by gileri** [comment]
What was that about ?!

**Comment by Bramas** [comment]
I found a bug. This must be fix quickly because i use it in production to controle some important devices that keep my zombie cat alive. 
The section of the code that prevent autonomous code duplication is buggy. This is against the second law of robotics and can create an army of zombie cats. 
I hope eloi is currently fixing this. I have no news from him since last night. He was supposed to feed my cat.
Oh my god. What have you created!!!! 
I must stop this conversation. I heard a strange voice at my door telling me my pizza is here but I did not order a pizza...
